spring:
  kafka:
    bootstrap-servers: kafka:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: xpayment-adapter-result-consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "ru.verlyshev.integration.xpayment.dto.XPaymentMessage"
    listener:
      ack-mode: manual
      concurrency: 1
  datasource:
    url: jdbc:postgresql://localhost:5432/payment-db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/iprody-lms

app:
  kafka:
    topics:
      xpayment-adapter:
        request: xpayment-adapter.requests
        response: xpayment-adapter.responses

logging:
  level:
    ru.verlyshev.service: DEBUG
    org.springframework.web: INFO
    org.springframework.data: INFO
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, loggers